import { io } from 'socket.io-client';

export const socket = io("/");

socket.on("connect", () => {
  console.log("connected to server");
});


socket.on("disconnect", () => {
  console.log("disconnected from server");
});

export enum SocketEventsEnums {
  RENDER_START = 'RENDER_START',
  RENDER_PROGRESS = 'RENDER_PROGRESS',
  RENDER_FINISH = 'RENDER_FINISH',
  RENDER_FAILED = 'RENDER_FAILED',
  COMPOSITION_START = 'COMPOSITION_START',
  COMPOSITION_PROGRESS = 'COMPOSITION_PROGRESS',
  COMPOSITION_FINISH = 'COMPOSITION_FINISH',
  COMPOSITION_FAILED = 'COMPOSITION_FAILED',
  YOUTUBE_UPLOAD_START = 'YOUTUBE_UPLOAD_START',
  YOUTUBE_UPLOAD_PROGRESS = 'YOUTUBE_UPLOAD_PROGRESS',
  YOUTUBE_UPLOAD_FINISH = 'YOUTUBE_UPLOAD_FINISH',
  YOUTUBE_UPLOAD_FAILED = 'YOUTUBE_UPLOAD_FAILED',
  YOUTUBE_UPLOAD_BATCH_START = 'YOUTUBE_UPLOAD_BATCH_START',
  YOUTUBE_UPLOAD_BATCH_PROGRESS = 'YOUTUBE_UPLOAD_BATCH_PROGRESS',
  YOUTUBE_UPLOAD_BATCH_FINISH = 'YOUTUBE_UPLOAD_BATCH_FINISH',
  YOUTUBE_UPLOAD_BATCH_FAILED = 'YOUTUBE_UPLOAD_BATCH_FAILED',
  YOUTUBE_PLAYLIST_ITEM_ADDED = 'YOUTUBE_PLAYLIST_ITEM_ADDED',
}
